# Generated by Django 6.0.4 on 2026-05-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0002_author_category_likes_news_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='status',
            field=models.CharField(choices=[('A', 'Admin'), ('U', 'User'), ('M', 'Manager')], default='U'),
        ),
    ]
